import type {
  User,
  Brand,
  Merchant,
  Store,
  Application,
  Module,
  Section,
  TaskType,
  Task,
  BpoProfile,
  SectionWebhook,
} from "@guaro/types";

// ─────────────────────────────────────────
// USERS
// ─────────────────────────────────────────

export const mockBpoProfiles: BpoProfile[] = [
  { id: "bpo-1", userId: "user-bpo-1", maxWeight: 10, activeWeight: 6 },
  { id: "bpo-2", userId: "user-bpo-2", maxWeight: 10, activeWeight: 9 },
  { id: "bpo-3", userId: "user-bpo-3", maxWeight: 10, activeWeight: 3 },
  { id: "bpo-4", userId: "user-bpo-4", maxWeight: 10, activeWeight: 0 },
];

export const mockUsers: User[] = [
  {
    id: "user-super-1",
    email: "superadmin@test.com",
    name: "Rodrigo Martínez",
    avatarUrl: null,
    role: "SUPERADMIN",
    team: "DIRECTOR",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "user-admin-1",
    email: "admin.catalog@test.com",
    name: "Laura González",
    avatarUrl: null,
    role: "ADMIN",
    team: "CATALOG",
    isActive: true,
    createdAt: "2026-01-02T00:00:00Z",
    adminProfile: {
      id: "admin-1",
      userId: "user-admin-1",
      moduleId: "module-catalog",
    },
  },
  {
    id: "user-1",
    email: "juan.ramirez@didi-labs.com",
    name: "Juan Ramírez",
    avatarUrl: null,
    role: "USER",
    team: "COMMERCIAL",
    isActive: true,
    createdAt: "2026-01-03T00:00:00Z",
  },
  {
    id: "user-bpo-1",
    email: "carlos.perez@didi-labs.com",
    name: "Carlos Pérez",
    avatarUrl: null,
    role: "BPO",
    team: "USER_GROWTH",
    isActive: true,
    createdAt: "2026-01-04T00:00:00Z",
    bpoProfile: mockBpoProfiles[0],
  },
  {
    id: "user-bpo-2",
    email: "maria.rodriguez@didi-labs.com",
    name: "María Rodríguez",
    avatarUrl: null,
    role: "BPO",
    team: "CATALOG",
    isActive: true,
    createdAt: "2026-01-04T00:00:00Z",
    bpoProfile: mockBpoProfiles[1],
  },
  {
    id: "user-bpo-3",
    email: "ana.lopez@didi-labs.com",
    name: "Ana López",
    avatarUrl: null,
    role: "BPO",
    team: "CATALOG",
    isActive: true,
    createdAt: "2026-01-05T00:00:00Z",
    bpoProfile: mockBpoProfiles[2],
  },
];

export const mockCurrentUser: User = mockUsers[2];

// ─────────────────────────────────────────
// MERCHANTS & BRANDS
// ─────────────────────────────────────────

export const mockMerchants: Merchant[] = [
  {
    id: "merchant-1",
    name: "Chedraui",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "merchant-2",
    name: "Cencosud",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "merchant-3",
    name: "Walmart",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "merchant-4",
    name: "Grupo Éxito",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
];

export const mockApplications: Application[] = [
  {
    id: "app-1",
    appName: "chedraui-mx-prod",
    country: "MX",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "app-2",
    appName: "cencosud-co-prod",
    country: "CO",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "app-3",
    appName: "walmart-cr-prod",
    country: "CR",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "app-4",
    appName: "exito-co-prod",
    country: "CO",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "app-5",
    appName: "cencosud-br-prod",
    country: "BR",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
];

export const mockBrands: Brand[] = [
  {
    id: "brand-1",
    name: "Chedraui",
    externalId: "CHD-001",
    merchantId: "merchant-1",
    merchant: mockMerchants[0],
    kaType: "KA",
    country: "MX",
    isSubBrand: false,
    pickingMode: "BAPP_PICKING",
    paymentMode: "PREPAID_CARD",
    menuMethod: "API",
    status: "ACTIVE",
    notes: "KA contact: Patricia Vargas",
    applications: [
      {
        id: "ba-1",
        brandId: "brand-1",
        applicationId: "app-1",
        application: mockApplications[0],
        isPrimary: true,
      },
    ],
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-05-14T00:00:00Z",
  },
  {
    id: "brand-2",
    name: "Chedraui Selecto",
    externalId: "CHD-002",
    merchantId: "merchant-1",
    merchant: mockMerchants[0],
    parentId: "brand-1",
    kaType: "KA",
    country: "MX",
    isSubBrand: true,
    pickingMode: "BAPP_PICKING",
    paymentMode: "PREPAID_CARD",
    menuMethod: "API",
    status: "ACTIVE",
    applications: [
      {
        id: "ba-2",
        brandId: "brand-2",
        applicationId: "app-1",
        application: mockApplications[0],
        isPrimary: true,
      },
    ],
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-05-10T00:00:00Z",
  },
  {
    id: "brand-3",
    name: "Cencosud CO",
    externalId: "CEN-CO-001",
    merchantId: "merchant-2",
    merchant: mockMerchants[1],
    kaType: "CKA",
    country: "CO",
    isSubBrand: false,
    pickingMode: "TWO_IN_ONE",
    paymentMode: "DIDI_PAYLESS",
    menuMethod: "SFTP",
    status: "ACTIVE",
    notes: "Billing cycle: last day of month",
    applications: [
      {
        id: "ba-3",
        brandId: "brand-3",
        applicationId: "app-2",
        application: mockApplications[1],
        isPrimary: true,
      },
    ],
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-05-15T00:00:00Z",
  },
  {
    id: "brand-4",
    name: "Metro",
    externalId: null,
    merchantId: "merchant-2",
    merchant: mockMerchants[1],
    parentId: "brand-3",
    kaType: "CKA",
    country: "CO",
    isSubBrand: true,
    status: "INACTIVE",
    applications: [
      {
        id: "ba-4",
        brandId: "brand-4",
        applicationId: "app-2",
        application: mockApplications[1],
        isPrimary: true,
      },
    ],
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-04-30T00:00:00Z",
  },
  {
    id: "brand-5",
    name: "Walmart CR",
    externalId: "WAL-CR-001",
    merchantId: "merchant-3",
    merchant: mockMerchants[2],
    kaType: "KA",
    country: "CR",
    isSubBrand: false,
    pickingMode: "DAPP_PICKING",
    paymentMode: "FOOD_MODE",
    menuMethod: "API",
    status: "ACTIVE",
    applications: [
      {
        id: "ba-5",
        brandId: "brand-5",
        applicationId: "app-3",
        application: mockApplications[2],
        isPrimary: true,
      },
    ],
    createdAt: "2026-01-25T00:00:00Z",
    updatedAt: "2026-05-13T00:00:00Z",
  },
  {
    id: "brand-6",
    name: "Éxito",
    externalId: "EXI-CO-001",
    merchantId: "merchant-4",
    merchant: mockMerchants[3],
    kaType: "CKA",
    country: "CO",
    isSubBrand: false,
    pickingMode: "BAPP_PICKING",
    paymentMode: "PREPAID_CARD",
    menuMethod: "BAPP",
    status: "ACTIVE",
    applications: [
      {
        id: "ba-6",
        brandId: "brand-6",
        applicationId: "app-4",
        application: mockApplications[3],
        isPrimary: true,
      },
    ],
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-05-12T00:00:00Z",
  },
  {
    id: "brand-7",
    name: "Carulla",
    externalId: null,
    merchantId: "merchant-4",
    merchant: mockMerchants[3],
    parentId: "brand-6",
    kaType: "CKA",
    country: "CO",
    isSubBrand: true,
    status: "PENDING",
    applications: [],
    createdAt: "2026-05-15T00:00:00Z",
    updatedAt: "2026-05-15T00:00:00Z",
  },
  {
    id: "brand-8",
    name: "Cencosud BR",
    externalId: "CEN-BR-001",
    merchantId: "merchant-2",
    merchant: mockMerchants[1],
    kaType: "CKA",
    country: "BR",
    isSubBrand: false,
    pickingMode: "TWO_IN_ONE",
    paymentMode: "DIDI_PAYLESS",
    menuMethod: "API",
    status: "ACTIVE",
    applications: [
      {
        id: "ba-7",
        brandId: "brand-8",
        applicationId: "app-5",
        application: mockApplications[4],
        isPrimary: true,
      },
    ],
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-05-11T00:00:00Z",
  },
];

export const mockStores: Store[] = [
  {
    id: "store-1",
    brandId: "brand-3",
    name: "Cencosud Chapinero",
    externalId: "CC-001",
    city: "Bogotá",
    country: "CO",
    isActive: true,
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-05-14T00:00:00Z",
  },
  {
    id: "store-2",
    brandId: "brand-3",
    name: "Cencosud Usaquén",
    externalId: "CC-002",
    city: "Bogotá",
    country: "CO",
    isActive: true,
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-05-14T00:00:00Z",
  },
  {
    id: "store-3",
    brandId: "brand-3",
    name: "Cencosud El Poblado",
    externalId: "CC-003",
    city: "Medellín",
    country: "CO",
    isActive: true,
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-05-12T00:00:00Z",
  },
  {
    id: "store-4",
    brandId: "brand-3",
    name: "Cencosud Laureles",
    externalId: "CC-004",
    city: "Medellín",
    country: "CO",
    isActive: false,
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-04-30T00:00:00Z",
  },
  {
    id: "store-5",
    brandId: "brand-3",
    name: "Cencosud Manga",
    externalId: "CC-005",
    city: "Cartagena",
    country: "CO",
    isActive: true,
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-05-10T00:00:00Z",
  },
];

// ─────────────────────────────────────────
// MODULES & SECTIONS
// ─────────────────────────────────────────

export const mockModules: Module[] = [
  {
    id: "module-catalog",
    name: "Catalog",
    description: "Gestión de catálogos, precios y stock",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "module-promos",
    name: "Promos",
    description: "Gestión de promociones",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "module-merchant",
    name: "Merchant Performance",
    description: "Performance y configuración de merchants",
    isActive: true,
    sortOrder: 3,
  },
];

export const mockSections: Section[] = [
  {
    id: "section-bapp",
    moduleId: "module-catalog",
    name: "BApp",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "section-sheets",
    moduleId: "module-catalog",
    name: "Spreadsheets Integration",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "section-promos",
    moduleId: "module-promos",
    name: "Promos",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "section-performance",
    moduleId: "module-merchant",
    name: "Performance",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "section-planning",
    moduleId: "module-merchant",
    name: "Planning",
    isActive: true,
    sortOrder: 2,
  },
];

export const mockTaskTypes: TaskType[] = [
  {
    id: "tt-upload-catalog",
    sectionId: "section-bapp",
    name: "Upload catalog",
    description: "Sube catálogo completo a BApp via API",
    executionMode: "AUTOMATED",
    formSchema: {},
    workflowDefinition: { nodes: [], edges: [] },
    assignmentStrategy: "WEIGHT_BALANCED",
    estimatedWeight: 4,
    slaHours: 4,
    maxConcurrentPerBpo: 2,
    retryAttempts: 3,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "tt-update-prices",
    sectionId: "section-bapp",
    name: "Update prices",
    description: "Actualiza precios via BApp API",
    executionMode: "AUTOMATED",
    formSchema: {},
    workflowDefinition: { nodes: [], edges: [] },
    assignmentStrategy: "WEIGHT_BALANCED",
    estimatedWeight: 3,
    slaHours: 3,
    maxConcurrentPerBpo: 2,
    retryAttempts: 3,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "tt-update-stock-bapp",
    sectionId: "section-bapp",
    name: "Update stock",
    description: "Actualiza stock via BApp API",
    executionMode: "AUTOMATED",
    formSchema: {},
    workflowDefinition: { nodes: [], edges: [] },
    assignmentStrategy: "WEIGHT_BALANCED",
    estimatedWeight: 3,
    slaHours: 3,
    maxConcurrentPerBpo: 2,
    retryAttempts: 3,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "tt-update-catalog-sheets",
    sectionId: "section-sheets",
    name: "Update catalog",
    description: "Actualiza catálogo desde spreadsheet",
    executionMode: "AUTOMATED",
    formSchema: {},
    workflowDefinition: { nodes: [], edges: [] },
    assignmentStrategy: "WEIGHT_BALANCED",
    estimatedWeight: 3,
    slaHours: 4,
    maxConcurrentPerBpo: 2,
    retryAttempts: 3,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "tt-update-stock-sheets",
    sectionId: "section-sheets",
    name: "Update stock",
    description: "Actualiza stock desde spreadsheet",
    executionMode: "AUTOMATED",
    formSchema: {},
    workflowDefinition: { nodes: [], edges: [] },
    assignmentStrategy: "WEIGHT_BALANCED",
    estimatedWeight: 3,
    slaHours: 3,
    maxConcurrentPerBpo: 2,
    retryAttempts: 3,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "tt-upload-promos",
    sectionId: "section-promos",
    name: "Upload promos",
    description: "Sube promociones via API",
    executionMode: "AUTOMATED",
    formSchema: {},
    workflowDefinition: { nodes: [], edges: [] },
    assignmentStrategy: "WEIGHT_BALANCED",
    estimatedWeight: 3,
    slaHours: 4,
    maxConcurrentPerBpo: 2,
    retryAttempts: 3,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "tt-business-hours",
    sectionId: "section-performance",
    name: "Update business hours",
    description: "Actualiza horarios de tiendas",
    executionMode: "AUTOMATED",
    formSchema: {},
    workflowDefinition: { nodes: [], edges: [] },
    assignmentStrategy: "WEIGHT_BALANCED",
    estimatedWeight: 2,
    slaHours: 3,
    maxConcurrentPerBpo: 3,
    retryAttempts: 3,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "tt-create-brand",
    sectionId: "section-planning",
    name: "Create brand",
    description: "Crea y configura un nuevo brand",
    executionMode: "HYBRID",
    formSchema: {},
    workflowDefinition: { nodes: [], edges: [] },
    assignmentStrategy: "KA_TYPE_BASED",
    estimatedWeight: 5,
    slaHours: 24,
    maxConcurrentPerBpo: 1,
    retryAttempts: 1,
    isActive: true,
    sortOrder: 1,
  },
];

// ─────────────────────────────────────────
// TASKS
// ─────────────────────────────────────────

export const mockTasks: Task[] = [
  {
    id: "task-1",
    taskTypeId: "tt-upload-catalog",
    taskType: mockTaskTypes[0],
    brandId: "brand-3",
    brand: mockBrands[2],
    createdById: "user-1",
    createdBy: mockUsers[2],
    assignedBpoId: "bpo-2",
    assignedBpo: { ...mockBpoProfiles[1], user: mockUsers[4] },
    status: "IN_PROGRESS",
    inputType: "SHEET_LINK",
    inputValue: "https://docs.google.com/spreadsheets/d/abc123",
    formData: { storesScope: "all", priority: "normal" },
    workflowInstanceId: "temporal-wf-001",
    assignedAt: "2026-05-15T09:00:00Z",
    startedAt: "2026-05-15T09:05:00Z",
    createdAt: "2026-05-15T08:58:00Z",
    updatedAt: "2026-05-15T09:05:00Z",
  },
  {
    id: "task-2",
    taskTypeId: "tt-upload-promos",
    taskType: mockTaskTypes[5],
    brandId: "brand-3",
    brand: mockBrands[2],
    createdById: "user-1",
    createdBy: mockUsers[2],
    assignedBpoId: "bpo-1",
    assignedBpo: { ...mockBpoProfiles[0], user: mockUsers[3] },
    status: "BLOCKED",
    inputType: "FILE_UPLOAD",
    inputValue: "promos_cencosud_may.xlsx",
    formData: {
      storesScope: "all",
      priority: "normal",
      notes: "Verificar duplicados",
    },
    blockReason: "47 filas con columnas faltantes: sku, precio_promo",
    workflowInstanceId: "temporal-wf-002",
    assignedAt: "2026-05-14T09:12:00Z",
    startedAt: "2026-05-14T09:14:00Z",
    blockedAt: "2026-05-14T09:14:05Z",
    createdAt: "2026-05-14T09:10:00Z",
    updatedAt: "2026-05-14T09:14:05Z",
    comments: [
      {
        id: "comment-1",
        taskId: "task-2",
        userId: "user-bpo-1",
        user: mockUsers[3],
        body: "El archivo tiene 47 filas sin SKU ni precio_promo. ¿Pueden mandar la versión corregida?",
        createdAt: "2026-05-14T09:20:00Z",
      },
    ],
  },
  {
    id: "task-3",
    taskTypeId: "tt-update-prices",
    taskType: mockTaskTypes[1],
    brandId: "brand-1",
    brand: mockBrands[0],
    createdById: "user-1",
    createdBy: mockUsers[2],
    status: "PENDING",
    inputType: "SHEET_LINK",
    inputValue: "https://docs.google.com/spreadsheets/d/xyz789",
    formData: { storesScope: "all", priority: "high" },
    createdAt: "2026-05-15T10:00:00Z",
    updatedAt: "2026-05-15T10:00:00Z",
  },
  {
    id: "task-4",
    taskTypeId: "tt-business-hours",
    taskType: mockTaskTypes[6],
    brandId: "brand-8",
    brand: mockBrands[7],
    createdById: "user-1",
    createdBy: mockUsers[2],
    assignedBpoId: "bpo-3",
    assignedBpo: { ...mockBpoProfiles[2], user: mockUsers[5] },
    status: "COMPLETED",
    inputType: "FILE_UPLOAD",
    inputValue: "horarios_cencosud_br.xlsx",
    formData: { storesScope: "all", priority: "normal" },
    result: {
      rows_processed: 87,
      rows_failed: 0,
      errors: [],
      duration_ms: 3200,
    },
    assignedAt: "2026-05-13T08:00:00Z",
    startedAt: "2026-05-13T08:02:00Z",
    completedAt: "2026-05-13T08:05:12Z",
    createdAt: "2026-05-13T07:58:00Z",
    updatedAt: "2026-05-13T08:05:12Z",
  },
  {
    id: "task-5",
    taskTypeId: "tt-create-brand",
    taskType: mockTaskTypes[7],
    brandId: "brand-7",
    brand: mockBrands[6],
    createdById: "user-1",
    createdBy: mockUsers[2],
    assignedBpoId: "bpo-1",
    assignedBpo: { ...mockBpoProfiles[0], user: mockUsers[3] },
    status: "IN_PROGRESS",
    inputType: "NONE",
    formData: {
      name: "Carulla",
      country: "CO",
      merchantId: "merchant-4",
      kaType: "CKA",
      pickingMode: "BAPP_PICKING",
      paymentMode: "PREPAID_CARD",
      menuMethod: "BAPP",
      isSubBrand: true,
      parentBrandId: "brand-6",
    },
    createdBrandId: "brand-7",
    assignedAt: "2026-05-15T11:00:00Z",
    startedAt: "2026-05-15T11:05:00Z",
    createdAt: "2026-05-15T10:58:00Z",
    updatedAt: "2026-05-15T11:05:00Z",
  },
];

// ─────────────────────────────────────────
// WEBHOOKS
// ─────────────────────────────────────────

export const mockWebhooks: SectionWebhook[] = [
  {
    id: "wh-1",
    sectionId: "section-planning",
    name: "Colombia ops",
    url: "https://hooks.example.com/co",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "wh-2",
    sectionId: "section-planning",
    name: "México ops",
    url: "https://hooks.example.com/mx",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "wh-3",
    sectionId: "section-promos",
    name: "Promos CO",
    url: "https://hooks.example.com/promos-co",
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
  },
];

// ─────────────────────────────────────────
// DEV SWITCHER
// ─────────────────────────────────────────

export const devUsers: Array<{ user: User; label: string }> = [
  { user: mockUsers[0], label: "Superadmin" },
  { user: mockUsers[1], label: "Admin · Catalog" },
  { user: mockUsers[2], label: "User · Commercial" },
  { user: mockUsers[3], label: "BPO · User Growth" },
  { user: mockUsers[4], label: "BPO · Catalog" },
];
